import type { Job } from "bullmq";
import { and, eq } from "drizzle-orm";
import { nanoid } from "nanoid";
import { db } from "../../db/index.js";
import { customers } from "../../db/schema/customers.js";
import { emailRoutingRules } from "../../db/schema/email-routing-rules.js";
import { invoiceBccForwards } from "../../db/schema/invoice-bcc-forwards.js";
import { QboClient } from "../../integrations/qb/client.js";
import { sendEmail } from "../../integrations/gmail/send.js";
import { createLogger } from "../../lib/logger.js";

const log = createLogger({ component: "jobs.forward-bcc" });

export type ForwardBccJobData = {
  docType: "invoice" | "salesreceipt";
  docId: string;       // QBO Id
  customerId: string;  // our local customer.id
};

export type ForwardBccJobResult = {
  sent: number;
  skipped: number;
  errors: number;
};

export async function forwardBccHandler(
  job: Job<ForwardBccJobData>,
): Promise<ForwardBccJobResult> {
  const { docType, docId, customerId } = job.data;
  log.info({ docType, docId, customerId }, "forward-bcc starting");

  // 1. Resolve customer's tags
  const custRows = await db
    .select({
      id: customers.id,
      displayName: customers.displayName,
      tags: customers.tags,
    })
    .from(customers)
    .where(eq(customers.id, customerId))
    .limit(1);

  if (custRows.length === 0) {
    log.warn({ customerId }, "customer not found; skipping forward");
    return { sent: 0, skipped: 0, errors: 0 };
  }
  const customer = custRows[0]!;
  const tags = (customer.tags as string[] | null) ?? [];
  if (tags.length === 0) return { sent: 0, skipped: 0, errors: 0 };

  // 2. Find matching routing rules — action='bcc_invoice' fires for both
  //    invoices and sales receipts.
  const rules = await db.select().from(emailRoutingRules);
  const matchingTargets = new Set<string>();
  for (const r of rules) {
    if (r.action !== "bcc_invoice") continue;
    if (tags.includes(r.tag.toLowerCase())) {
      matchingTargets.add(r.value);
    }
  }
  if (matchingTargets.size === 0) {
    return { sent: 0, skipped: 0, errors: 0 };
  }

  // 3. Skip targets we've already forwarded to for this doc
  const existing = await db
    .select({ targetEmail: invoiceBccForwards.targetEmail })
    .from(invoiceBccForwards)
    .where(
      and(
        eq(invoiceBccForwards.docType, docType),
        eq(invoiceBccForwards.docId, docId),
      ),
    );
  const alreadyForwarded = new Set(existing.map((r) => r.targetEmail));
  const targets = [...matchingTargets].filter((t) => !alreadyForwarded.has(t));
  if (targets.length === 0) {
    return { sent: 0, skipped: matchingTargets.size, errors: 0 };
  }

  // 4. Fetch PDF from QBO
  const qbClient = new QboClient();
  const pdfBuffer = await qbClient.getPdf(
    docType === "invoice" ? "invoice" : "salesreceipt",
    docId,
  );

  // 5. Send one email per target
  const docLabel = docType === "invoice" ? "Invoice" : "Sales Receipt";
  let sent = 0;
  let errors = 0;
  for (const target of targets) {
    try {
      const result = await sendEmail({
        to: target,
        subject: `[FYI — copy] ${docLabel} for ${customer.displayName}`,
        text: `This is an automated copy of the ${docLabel.toLowerCase()} QuickBooks just sent to ${customer.displayName}. The PDF is attached.\n\nGenerated by finance-hub as a workaround for QBO's BCC field.`,
        html: `<p>This is an automated copy of the ${docLabel.toLowerCase()} QuickBooks just sent to <strong>${customer.displayName}</strong>. The PDF is attached.</p><p style="color:#666;font-size:0.9em">Generated by finance-hub as a workaround for QBO's BCC field.</p>`,
        attachments: [
          {
            filename: `${docType}-${docId}.pdf`,
            mimeType: "application/pdf",
            data: pdfBuffer,
          },
        ],
      });
      // Insert tracking row — unique constraint protects against races
      await db.insert(invoiceBccForwards).values({
        id: nanoid(24),
        docType,
        docId,
        customerId,
        targetEmail: target,
        gmailMessageId: result.messageId,
      });
      sent++;
    } catch (err) {
      log.warn({ err, docType, docId, target }, "forward-bcc send failed");
      errors++;
    }
  }

  log.info(
    { docType, docId, customerId, sent, skipped: alreadyForwarded.size, errors },
    "forward-bcc complete",
  );
  return { sent, skipped: alreadyForwarded.size, errors };
}
