// Agent report generation (spec §9): the model supplies STRUCTURED
// content (title/sections/tables); this renders it through a fixed
// house-styled react-pdf template — the model never writes layout.
// CSV is the tabular sibling. Artifacts persist to data/agent-reports/
// with agent_reports rows (the /agent library).

import { existsSync } from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import React from "react";
import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer";
import { nanoid } from "nanoid";
import { db } from "../../db/index.js";
import { agentReports } from "../../db/schema/agent.js";

export const AGENT_REPORTS_DIR = path.resolve("data", "agent-reports");

// Mirrors the statement PDF palette so reports look like house documents.
const COLOR_TITLE = "#5B9BD5";
const COLOR_TEXT = "#1F2937";
const COLOR_LABEL = "#6B7280";
const COLOR_BORDER = "#E5E7EB";
const COLOR_TABLE_HEADER_BG = "#5B9BD5";
const COLOR_TABLE_HEADER_TEXT = "#FFFFFF";
const COLOR_ROW_ALT = "#F8F8F8";

export type ReportSection = {
  heading?: string;
  text?: string;
  table?: { columns: string[]; rows: string[][] };
};

export type ReportContent = {
  title: string;
  subtitle?: string;
  sections: ReportSection[];
};

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 9, color: COLOR_TEXT, fontFamily: "Helvetica" },
  title: { fontSize: 16, color: COLOR_TITLE, marginBottom: 2 },
  subtitle: { fontSize: 9, color: COLOR_LABEL, marginBottom: 12 },
  heading: { fontSize: 11, color: COLOR_TITLE, marginTop: 10, marginBottom: 4 },
  para: { marginBottom: 6, lineHeight: 1.4 },
  table: { marginTop: 4, marginBottom: 8 },
  tr: { flexDirection: "row" },
  th: {
    backgroundColor: COLOR_TABLE_HEADER_BG,
    color: COLOR_TABLE_HEADER_TEXT,
    padding: 4,
    fontSize: 8,
    flexGrow: 1,
    flexBasis: 0,
  },
  td: {
    padding: 4,
    fontSize: 8,
    flexGrow: 1,
    flexBasis: 0,
    borderBottomWidth: 0.5,
    borderBottomColor: COLOR_BORDER,
  },
  tdAlt: { backgroundColor: COLOR_ROW_ALT },
  footer: {
    position: "absolute",
    bottom: 18,
    left: 36,
    right: 36,
    fontSize: 7,
    color: COLOR_LABEL,
    textAlign: "center",
  },
});

function ReportDoc({ content, generatedAt }: { content: ReportContent; generatedAt: Date }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{content.title}</Text>
        <Text style={styles.subtitle}>
          {content.subtitle ? `${content.subtitle} · ` : ""}
          Generated {generatedAt.toISOString().slice(0, 10)} · Feldart Finance Hub
        </Text>
        {content.sections.map((s, i) => (
          <View key={i} wrap={false}>
            {s.heading ? <Text style={styles.heading}>{s.heading}</Text> : null}
            {s.text ? <Text style={styles.para}>{s.text}</Text> : null}
            {s.table ? (
              <View style={styles.table}>
                <View style={styles.tr}>
                  {s.table.columns.map((c, ci) => (
                    <Text key={ci} style={styles.th}>
                      {c}
                    </Text>
                  ))}
                </View>
                {s.table.rows.map((row, ri) => (
                  <View key={ri} style={styles.tr}>
                    {row.map((cell, ci) => (
                      <Text
                        key={ci}
                        style={ri % 2 ? [styles.td, styles.tdAlt] : styles.td}
                      >
                        {cell}
                      </Text>
                    ))}
                  </View>
                ))}
              </View>
            ) : null}
          </View>
        ))}
        <Text style={styles.footer} fixed>
          Generated by the Feldart Finance Hub agent — verify figures before
          external use.
        </Text>
      </Page>
    </Document>
  );
}

export function csvEscape(cell: string): string {
  if (/[",\n\r]/.test(cell)) return `"${cell.replace(/"/g, '""')}"`;
  return cell;
}

export function buildCsv(columns: string[], rows: string[][]): string {
  const lines = [columns.map(csvEscape).join(",")];
  for (const row of rows) lines.push(row.map(csvEscape).join(","));
  return lines.join("\r\n") + "\r\n";
}

export type SaveReportInput = {
  kind: "pdf" | "csv";
  title: string;
  conversationId: string | null;
  requestedByUserId: string | null;
  buffer: Buffer;
};

export async function saveAgentReport(
  input: SaveReportInput,
): Promise<{ id: string }> {
  const id = nanoid(24);
  const rel = `${id}.${input.kind}`;
  if (!existsSync(AGENT_REPORTS_DIR)) {
    await fs.mkdir(AGENT_REPORTS_DIR, { recursive: true });
  }
  await fs.writeFile(path.join(AGENT_REPORTS_DIR, rel), input.buffer);
  await db.insert(agentReports).values({
    id,
    conversationId: input.conversationId,
    requestedByUserId: input.requestedByUserId,
    title: input.title.slice(0, 256),
    kind: input.kind,
    storagePath: rel,
  });
  return { id };
}

export async function renderReportPdf(
  content: ReportContent,
  generatedAt = new Date(),
): Promise<Buffer> {
  return renderToBuffer(<ReportDoc content={content} generatedAt={generatedAt} />);
}

export async function readAgentReportBytes(storagePath: string): Promise<Buffer> {
  const full = path.resolve(AGENT_REPORTS_DIR, storagePath);
  if (!full.startsWith(AGENT_REPORTS_DIR)) throw new Error("invalid storage path");
  return fs.readFile(full);
}
